# Generated by Django 4.2.10 on 2024-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comment_options_recipe_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_post',
            name='title',
            field=models.CharField(max_length=200, unique='true'),
        ),
    ]
